FROM node:16

WORKDIR /opt/backstage

COPY package.json ./package.json

RUN apt-get update && apt-get install -y --no-install-recommends netcat \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN npm install

COPY src/ .

CMD ["npm", "start"]
